### ISSUE TITLE
Where can we get the "texture_floor" files?

### ISSUE THREAD

**Issue by mat-macnica** [NVIDIA-AI-IOT/robot_freespace_seg_Isaac_TAO#2]
Hi,

I tried to run below notebook with isaac_sim-2021.2.1 and tao-toolkit(Version 3.22.05).
 "freespace_segmentation.ipynb"

And, We found below error;

![tao-err](https://user-images.githubusercontent.com/92834689/184818927-be13a148-8b8f-43d1-8fea-7f3b577c8596.PNG)

Question:
  Where can we get the "texture_floor" files?

Best regards,

**Comment by RishabhChadha-97** [comment]
Hi Mat,

In the notebook step 2 B mentions modifying the YAML file for the corresponding environments so that the correct textures are loaded according to where you have stored them. We do not provide the texture files in this repository, you can use any images which are similar to the real world where you want to deploy the model. You can also use Textures which are provided as samples with Isaac Sim.

**Comment by mat-macnica** [comment]
Hi,

Thank you very much for your kindness.
I really appreciate your help.

I'd like to check the behavior with your guide.

Best regards,
